export type ModelInfo = {
  slug: string;
  number: string;
  name: string;
  english: string;
  family: "回歸" | "分類" | "分群" | "降維" | "深度學習";
  summary: string;
  industry: string;
  bestFor: string[];
  avoidWhen: string[];
  parameters: string[];
  metrics: string[];
  preprocessing: string;
  interpretability: "高" | "中" | "低";
  trainingCost: "低" | "中" | "高";
  lab?: "ridge" | "logistic" | "decision-tree" | "svm" | "knn" | "kmeans";
};

export const models: ModelInfo[] = [
  {
    slug: "linear-regression",
    number: "01",
    name: "線性回歸",
    english: "Linear / Ridge Regression",
    family: "回歸",
    summary: "用透明係數建立數值預測基準，先確認方向、誤差與資料是否具有可預測性。",
    industry: "房價估值、需求量、耗能與製程週期預測",
    bestFor: ["連續數值目標", "需要解釋方向與幅度", "建立非模型基準後的第一個模型"],
    avoidWhen: ["關係高度非線性", "重要交互作用難以事先設計", "只關心極端尾部"],
    parameters: ["Ridge alpha", "特徵轉換", "交互作用"],
    metrics: ["MAE", "RMSE", "R²", "分族群誤差"],
    preprocessing: "缺失處理、類別編碼；使用正則化時需標準化",
    interpretability: "高",
    trainingCost: "低",
    lab: "ridge",
  },
  {
    slug: "logistic-regression",
    number: "02",
    name: "邏輯回歸",
    english: "Logistic Regression",
    family: "分類",
    summary: "輸出可校準的事件風險分數，適合風控、流失與品質判斷的透明基準。",
    industry: "金融覆核、病患風險分層、批次加驗",
    bestFor: ["二元分類", "需要機率與係數解釋", "需要依人工容量設定門檻"],
    avoidWhen: ["邊界高度非線性", "交互作用非常多", "未處理嚴重類別不平衡"],
    parameters: ["C", "penalty", "classification threshold"],
    metrics: ["PR-AUC", "Precision", "Recall", "Calibration"],
    preprocessing: "標準化、類別編碼、缺失處理",
    interpretability: "高",
    trainingCost: "低",
    lab: "logistic",
  },
  {
    slug: "decision-tree",
    number: "03",
    name: "決策樹",
    english: "Decision Tree",
    family: "分類",
    summary: "以可閱讀的 if-then 規則捕捉非線性與交互作用，適合和領域專家一起檢視。",
    industry: "製程加驗規則、客服路由、風險初篩",
    bestFor: ["需要可讀規則", "存在非線性切點", "希望示範過度擬合"],
    avoidWhen: ["單棵樹預測不穩定", "規則深到無法閱讀", "只追求最高泛化效果"],
    parameters: ["max_depth", "min_samples_leaf", "criterion"],
    metrics: ["Validation accuracy", "F1", "Generalization gap"],
    preprocessing: "缺失與類別處理；通常不需標準化",
    interpretability: "高",
    trainingCost: "低",
    lab: "decision-tree",
  },
  {
    slug: "random-forest",
    number: "04",
    name: "隨機森林",
    english: "Random Forest",
    family: "分類",
    summary: "用多棵隨機樹降低單樹不穩定，常是表格資料可靠且調參負擔低的強基準。",
    industry: "設備風險、醫療排序、非線性估值與需求預測",
    bestFor: ["表格資料", "非線性與交互作用", "希望取得穩健基準"],
    avoidWhen: ["需要直接係數解釋", "模型大小與延遲限制嚴格", "高維稀疏文字"],
    parameters: ["n_estimators", "max_depth", "max_features"],
    metrics: ["PR-AUC", "Permutation importance", "Latency"],
    preprocessing: "缺失與類別處理；不必標準化",
    interpretability: "中",
    trainingCost: "中",
  },
  {
    slug: "svm",
    number: "05",
    name: "支持向量機",
    english: "Support Vector Machine",
    family: "分類",
    summary: "以最大間隔建立分類邊界，適合樣本中等、維度高且邊界相對清楚的資料。",
    industry: "IC 測試訊號、頻譜、文本與生物資料分類",
    bestFor: ["中型高維資料", "邊界可能非線性", "樣本數尚可控制"],
    avoidWhen: ["資料非常大", "需直接輸出規則", "沒有一致標準化"],
    parameters: ["C", "gamma", "kernel"],
    metrics: ["F1", "Support vector ratio", "Inference latency"],
    preprocessing: "必須標準化；類別與缺失需處理",
    interpretability: "低",
    trainingCost: "中",
    lab: "svm",
  },
  {
    slug: "knn",
    number: "06",
    name: "K-近鄰演算法",
    english: "K-Nearest Neighbors",
    family: "分類",
    summary: "以歷史相似案例投票或平均，直觀但高度依賴尺度、距離與資料維度。",
    industry: "相似會員、商品推薦、維修歷史案例檢索",
    bestFor: ["資料量不大", "相似案例有清楚意義", "希望展示局部決策"],
    avoidWhen: ["高維資料", "即時延遲嚴格", "無關特徵很多"],
    parameters: ["k", "weights", "distance metric"],
    metrics: ["F1", "Accuracy", "Inference latency"],
    preprocessing: "必須標準化與移除無關特徵",
    interpretability: "中",
    trainingCost: "低",
    lab: "knn",
  },
  {
    slug: "naive-bayes",
    number: "07",
    name: "單純貝氏",
    english: "Naive Bayes",
    family: "分類",
    summary: "在高維稀疏文字中建立快速基準，適合客服信件與文件主題分流。",
    industry: "客服信件分類、異常報告分流、垃圾訊息判定",
    bestFor: ["詞頻與稀疏文字", "需要極快訓練與推論", "建立文字分類基準"],
    avoidWhen: ["語境與詞序很重要", "特徵依賴性強", "直接把輸出當真實機率"],
    parameters: ["alpha", "feature representation", "class prior"],
    metrics: ["Macro F1", "PR-AUC", "低信心比例"],
    preprocessing: "斷詞、TF-IDF／詞頻、模板與個資清理",
    interpretability: "中",
    trainingCost: "低",
  },
  {
    slug: "kmeans",
    number: "08",
    name: "K-Means 分群",
    english: "K-Means Clustering",
    family: "分群",
    summary: "以質心探索自然群組，成功標準是形成可執行的差異策略，而非只追求數學分數。",
    industry: "會員 RFM、門市分型、設備運轉模式",
    bestFor: ["沒有標籤", "群組近似球狀", "需要可描述質心"],
    avoidWhen: ["群組密度與形狀差異大", "離群值很多", "分群無法導向行動"],
    parameters: ["k", "initialization", "n_init"],
    metrics: ["Silhouette", "群組穩定度", "可行動性"],
    preprocessing: "標準化、偏態轉換、離群值分析",
    interpretability: "中",
    trainingCost: "低",
    lab: "kmeans",
  },
  {
    slug: "pca",
    number: "09",
    name: "主成分分析",
    english: "Principal Component Analysis",
    family: "降維",
    summary: "將高度相關特徵壓縮為少數正交方向，用於視覺化、去共線性或加速下游模型。",
    industry: "多感測器製程監控、生物特徵、風險因子壓縮",
    bestFor: ["特徵高度相關", "需要壓縮與視覺化", "下游模型成本過高"],
    avoidWhen: ["每個原始特徵都要直接解釋", "低變異訊號很重要", "關係高度非線性"],
    parameters: ["n_components", "svd_solver", "whitening"],
    metrics: ["解釋變異", "下游模型表現", "壓縮率"],
    preprocessing: "通常先標準化，且必須放入交叉驗證流程",
    interpretability: "低",
    trainingCost: "中",
  },
  {
    slug: "neural-networks",
    number: "10",
    name: "類神經網路",
    english: "Neural Networks / Deep Learning",
    family: "深度學習",
    summary: "在大量影像、語音、長文本與複雜模式上學習表示，但需要更多資料、算力與維運責任。",
    industry: "AOI 瑕疵、醫療影像、文本摘要、多變量時序",
    bestFor: ["非結構化資料", "資料與算力充足", "簡單模型已證明不足"],
    avoidWhen: ["小型表格資料", "必須高度透明", "缺乏部署與監控資源"],
    parameters: ["learning rate", "network capacity", "regularization"],
    metrics: ["Learning curve", "Task metric", "Latency", "Resource usage"],
    preprocessing: "依資料型態正規化、版本化與資料增強",
    interpretability: "低",
    trainingCost: "高",
  },
];

export const modelBySlug = new Map(models.map((model) => [model.slug, model]));

export const industries = [
  { name: "半導體與製造", detail: "良率風險、設備預警與工程師覆核量", models: ["決策樹", "隨機森林", "SVM"] },
  { name: "金融風控", detail: "違約／詐欺排序、門檻與人工審查成本", models: ["邏輯回歸", "隨機森林", "單純貝氏"] },
  { name: "智慧醫療", detail: "風險分層、召回率與人工覆核", models: ["邏輯回歸", "隨機森林", "類神經網路"] },
  { name: "零售電商", detail: "會員分群、需求預測與相似案例", models: ["K-Means", "KNN", "線性回歸"] },
  { name: "房地產與需求", detail: "透明估值、區域誤差與穩定預測", models: ["線性回歸", "隨機森林", "PCA"] },
];
